server:
  port: 8888
system:
  version: 1.0.0
  pdaServiceUrl: http://127.0.0.1:9999
  pcServiceUrl: http://192.168.1.50:9081/
  adb: ${cacheFolder}/jdk/bin

# Sqlite数据库配置
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  datasource:
    url: jdbc:sqlite:${cacheFolder}/yznpdazs.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    # druid相关配置
    druid:
      serverTimezone: CTT
      # 连接池初始化大小
      initial-size: 8
      # 最大活跃连接数
      max-active: 20
      # 最小空闲连接数
      min-idle: 1
      # 获取连接等待超时的时间
      max-wait: 60000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，ms
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      # 配置过滤器，https://github.com/alibaba/druid/wiki/%E5%86%85%E7%BD%AEFilter%E7%9A%84%E5%88%AB%E5%90%8D
      filters: stat,slf4j,config
  # 配置mapper文件路径
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:mapper/*.xml

cacheFolder: ${user.home}/yznpdazs
logFolder: ${cacheFolder}/logs/
pc:
  tbpcs: 500
